server:
#  http端口号
#详情 TomcatHttpConfig http重定向 https （this配置文件无法配置两个端口 ）
#  http2:
#    enabled: true
  port: 443
  servlet:
#    uri根目录
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
  ssl:

    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: mykey

spring:
  datasource:
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    mysql连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lims?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 123456
    username: root

  jpa:
#    默认开启标警告
    open-in-view: false
mybatis:
#  映射文件位置
  mapper-locations: classpath:/mapper/*.xml
#  别名 不会用
#  type-aliases-package: com.example.lims.modules.*.entity.*
debug: true
