server:
  #  http端口号
  port: 8888
  servlet:
    #    uri根目录
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
spring:
  datasource:
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #    mysql连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lims?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    password: 123456
    username: root

mybatis:
  #  映射文件位置

  mapper-locations: classpath:/mapper/*.xml
#  configuration:

  ##  别名
  type-aliases-package: com.example.demo.modules.entity
  configuration:
    ##    #无自定义映射的是否开启自动驼峰命名规则（camel case）映射，db字段名：last_name javabean属性名:lastName
    map-underscore-to-camel-case: true
    #开启延迟加载
    lazy-loading-enabled: true
logging:
  config: classpath:log4j2-demo.xml
debug: true